### PR TITLE
ACME protocol updates (RFC8555)

### PR DESCRIPTION
**Pull request by mmaney**
Works to issue certificate from staging environment.

### CODE REVIEW

**Comment by mmaney** [comment]
I came top realize that, contrary to what I had been thinking, the RFC8555 were now the most urgent changes.  With these in place I can actually test the protocol implementation, not just that the far end of a lever moves when I push down on the near end.  And not being able to do that was deterring me from considering other work finished enough for a PR.

@komuw, please sanity check me ASAP.  I can't see any reason not to merge, but if I could see it I would have fixed it.  :-)

Oh, wait, I forgot that one detail.  Wanted to get rid of the obviously obsolete Py2 versions listed in setup.py and add at least through 3.7.  Any other thoughts on that?

@AlecTroemel @kylejohnson , please check me if you have time.  You've both kept me thinking in prior discussions.  The work that follows this will be of more direct interest to you as challenge provider authors.  And of course anyone else, I'm sure I'm forgetting someone here...

**Comment by mmaney** [comment]
After poking about, there are changes to the typing module that landed in 3.6, but they've been backported (it says) to 3.5.  I'm not using var annotations yet, but I also would not pretend to promise that I won't.  So 3.5 seems a reasonable lower bound, in theory.

Just the opportunistic annotations I've added have already caught a few little glitches, and mypy runs a good deal quicker than running unittests... and gives clear error messages, not piles of tracebacks to wade through in search of the root cause.  Granted that I am not a fan of mocked-up tests, but so far annotations seem to be have at least an order of magnitude better ROI.  So, nope, no promise from me not to make further use of them.

**Comment by kylejohnson** [comment]
I'm not up to speed on the RFC8555 updates currently, so unfortunately I can't comment on those changes.

I am however all for getting rid of python 2.7, and adding in new features fro 3.6 - like variable annotations.  Unit tests and mockups still have their place, of course, but if variable annotations make our lives easier, than they are worth using.

On the subject of "make our lives easier", I'm currently at the tail-end of generating 350,000 SSL certificates with a custom-built python application that has sewer at the center (hence my interest in this project).  In generating those 350k certs, my life has been far from easy, and I've added and modified a ton of sewer's code around logging and monitoring, so I will likely have a PR or two around that, in the near future.

**Comment by mmaney** [comment]
@kylejohnson the protocol changes are, to a first approximation, all GET requests turn into signed requests - no signed content, but reusing the existing mechanism to make forgery much more difficult.  Which means they become PUT requests, or "put as get" as they call it.  Anyway, this code has been run successfully against LE's staging, and my short list before merging includes setting up some unimportant (in case it breaks somehow) identity to test against production.

Also, and beyond this, feel free to tell me about the rough edges you're running into.  I have quite the pile of old bugs and changes (and some of them match up, even) in the in basket, and the more the merrier!  Sometimes they even help solve each other.

**Comment by aphexer** [comment]
FWIW, I took the code from the PR and using it now. Works for me.

**Pull request merged**
