### PR TITLE
Use unittest.mock in place of external module.  Requires Python 3.3+

### PR DESCRIPTION
**Pull request by mmaney**
Contributor offers to license certain software (a “Contribution” or multiple
“Contributions”) to sewer, and sewer agrees to accept said Contributions,
under the terms of the MIT License.
Contributor understands and agrees that sewer shall have the irrevocable and perpetual right to make
and distribute copies of any Contribution, as well as to create and distribute collective works and
derivative works of any Contribution, under the MIT License.

See bug #151

### CODE REVIEW

**Comment by mmaney** [comment]
Ah, the other tests finally heard from.  Komuw, this lets me run unittests here, but the trivial patch in the PR ought to have complementary changes in a couple places in areas that I'm not familar enough with (and have no way to test) to feel comfortable changing.  Don't need mock as a dep in setup, and the vagrant and circleci stuff I'd guess, but the devil is usually in the details.

**Comment by mmaney** [comment]
Oh geeze, I forgot about the dns drivers' tests.  Just change the imports to bind the stdlib mock, yes?

**Comment by mmaney** [comment]
If you like this, I'm going to rearrange the pieces that go into smart-nonces in order to take the shortest path towards merging a cleaned-up RFC8555 and getting testing against pebble going.  I think something like this:

1. this patch, so I can run existing tests locally and hopefully stop tripping them after placing the PR :-/
2. the request wrappers, either refactored or with the hack at the end of the current series so they work with current tests [NOT including the HEAD fix to get_nonce for now]

... not sure if the next steps can be usefully pulled apart in any meaningful way.  Can't test RFC8555 protocol changes without pebble, can't work against pebble (1) without RFC8555 and adding the ability to not check the server's certificate (the first cause for the wrappers).  Yeah, this likely breaks the existing tests at some point, but my personal bias has always been towards integration-level testing, and since these changes are centered about RFC8555, it's hard for me to get motivated about mocks that omit any actual test of the protocol... even more so because that level of testing was how I corrected many errors in my understanding of the RFC and the various changes that LE's staging server currently implements.

Oh, and a dummy dns_provider (pebble can be told to assume challenges are met, I believe) - there's one of those somewhere in the tests already IIRC.

(1) And as I'm writing this it occurs to me: without RFC8555 we can still hit pebble for the directory and maybe a few of the queries that were already signed PUTs?  That might make a reasonable step to test that the pebble-accepting changes are working before the larger post-as-get changes go in....

**Comment by komuw** [comment]
this PR looks okay. 
you can go ahead and merge, when you are okay with it

**Pull request merged**
