### PR TITLE
dns_providers: fix acme challenge dns record for AliyunDNS

### PR DESCRIPTION
**Pull request by menduo**
Thank you for contributing to sewer.                    
Every contribution to sewer is important to us.                       
You may not know it, but you have just contributed to making the world a more safer and secure place.                         

Contributor offers to license certain software (a “Contribution” or multiple
“Contributions”) to sewer, and sewer agrees to accept said Contributions,
under the terms of the MIT License.
Contributor understands and agrees that sewer shall have the irrevocable and perpetual right to make
and distribute copies of any Contribution, as well as to create and distribute collective works and
derivative works of any Contribution, under the MIT License.

Now,                   

## What(What have you changed?)

`sewer/dns_providers/aliyundns.py` and `sewer/dns_providers/hurricane.py`

Fix `_acme-challenge ` record name for request DNS create_dns_recored.

## Why(Why did you change it?)

for `aliyundns.py`: the old code does not work on domain like `*.menduo.net` or `menduo.net`, but works good on `*.test.menduo.net` or `test.menduo.net`.

for `hurricane.py`: both the new and old code works good,  the new code are more consistent.

Related issue: Error on send_csr #102 

fixes; https://github.com/komuw/sewer/issues/102

### CODE REVIEW

**Comment by komuw** [comment]
@menduo 

because of https://github.com/komuw/sewer/issues/102 
do you mind adding a testcase that will ensure the issue found in https://github.com/komuw/sewer/issues/102 is fixed by this PR and prevent it from re-occuring

**Comment by menduo** [comment]
@komuw Yes. I'm not familiar with the `mock` package, but I'll try to add some tests later.

**Comment by komuw** [comment]
@menduo 
since this PR only makes changes to the `extract_zone` methods; you don't have to necessarily use mock:
- you could just right a unit tests(one for hurricane and another for aliyun)  asserting that they return what you expect them to return

**Comment by menduo** [comment]
@komuw Added tests for `extract_zone`, both aliyudns and hedns.

**Comment by komuw** [comment]
@menduo Thanks. 
I'll merge and release on pypi over the weekend.

**Pull request merged**
