### PR TITLE
ECDSA support.

### PR DESCRIPTION
**Pull request by jfb**
## What(What have you changed?)

add ECDSA support.

## Why(Why did you change it?)

ECDSA better than RSA.

https://github.com/komuw/sewer/issues/202

### CODE REVIEW

**Comment by jfb** [comment]
@mmaney 

Default use RSA

```python
import sewer.client
client = sewer.client.Client("example.com")
```

use ECDSA

```python
import sewer.client
client = sewer.client.Client("example.com", curves="secp256r1")
```

**Comment by mmaney** [comment]
More to the point, the code in create_certificate has a conditional part that my eyes apparently skipped right over.  Late night, perhaps not enough coffee this morning.

It needs test(s) for the new method, which should be easy to add.  It will also need support in cli.py, which is probably where that little voice whispering that there's more to be done around loading and saving non-RSA keys is coming from.  And if it had all that in place it would still wait until after 0.8.3 is out. :-/

And in that longer timeframe, there's a goal to get rid of the one or two uses of the... disparaged would be the word, I think, for OpenSsl.crypto, moving to the suggested cryptography library (as you've used in this).  And along the way to that goal I expect all the crypto methods will wind up in a sewer.crypto library - this is one part of a general housecleaning and breakup of the global Client namespace that the code lives in now in favor of more cohesive classes.  Maybe I can put the initial refactor into crypto.py near the top of the list post-release.  Would you be interested in working on that, or are you just focused on the EC keys?  (thinking about that, they can be used for the account keys on the LE side now, no?)

**Comment by mmaney** [comment]
@jfb  It was sticky - I kept coming back to this bit of work.  The crypto branch is intended to be merged into the trunk for the 0.8.4 release.  Does this take care of your use cases satisfactorily?  Aside from the testing and linting (and a mypy check that isn't incorporated into the test suite yet), I've generated a certificate with an EC key from staging.

**Comment by mmaney** [comment]
Oops... never tested with an EC account key (I knew there were other things that needed attention) and that's not working yet.  :-(

**Comment by jfb** [comment]
@mmaney Thank you for all you have done for us!

**Pull request closed without merging**
