### PR TITLE
Added Rackspace DNS 

### PR DESCRIPTION
**Pull request by m4ldonado**
Thank you for contributing to sewer.                    
Every contribution to sewer is important to us.                       
You may not know it, but you have just contributed to making the world a more safer and secure place.                         

Contributor offers to license certain software (a “Contribution” or multiple
“Contributions”) to sewer, and sewer agrees to accept said Contributions,
under the terms of the MIT License.
Contributor understands and agrees that sewer shall have the irrevocable and perpetual right to make
and distribute copies of any Contribution, as well as to create and distribute collective works and
derivative works of any Contribution, under the MIT License.

Now,                   

## What(What have you changed?)
Added rackspace dns support

## Why(Why did you change it?)
It's what I use and it's part of this issue:
https://github.com/komuw/sewer/issues/59

### CODE REVIEW

**Comment by komuw** [comment]
hi @m4ldonado . 
Thanks for contributing. 

1. Could you add some tests? Have a look at https://github.com/komuw/sewer/tree/master/sewer/dns_providers/tests 
to see how the other DNS providers are tested. 

2. Also add rackspace to the README; https://github.com/komuw/sewer/blob/master/README.md

**Comment by m4ldonado** [comment]
@komuw Thanks for the pointers.  Will do

**Comment by m4ldonado** [comment]
Will update Readme now

**Comment by m4ldonado** [comment]
hi @komuw,

Sorry this took a while - I've replicated some of the tests from the test directory. I'm happy to add anything else that's missing

**Comment by komuw** [comment]
@m4ldonado thanks!
this is now in the latest release:  
1. https://pypi.org/project/sewer/0.6.0/  
2. https://github.com/komuw/sewer/releases/tag/0.6.0

**Pull request merged**
