### PR TITLE
Global logger

### PR DESCRIPTION
**Pull request by SN9NV**
Thank you for contributing to sewer.                    
Every contribution to sewer is important to us.                       
You may not know it, but you have just contributed to making the world a more safer and secure place.                         

Contributor offers to license certain software (a “Contribution” or multiple
“Contributions”) to sewer, and sewer agrees to accept said Contributions,
under the terms of the MIT License.
Contributor understands and agrees that sewer shall have the irrevocable and perpetual right to make
and distribute copies of any Contribution, as well as to create and distribute collective works and
derivative works of any Contribution, under the MIT License.

Now,                   

## What(What have you changed?)
Made logger a global that gets imported into all the classes that want it.

## Why(Why did you change it?)
Setting up the logger in multiple places causes lines to be printed twice and the user can set up their own logger and have sewer use it.

### CODE REVIEW

**Comment by etienne-napoleone** [comment]
I'm not sure to get what's the point of doing it this way.
The python logging library already provides everything needed to manage different loggers.

**Comment by SN9NV** [comment]
I made the library work for me, so I decided to share it. I guess I changed more than just make the logger once. If there are better ways to do things and the author wants me to change something, then I will change it.

**Comment by etienne-napoleone** [comment]
I made some basic changes that helps using logging the "right" way in #125 .
If you have any remark feel free to comment!

**Comment by komuw** [comment]
Hi @SN9NV 

Thanks for contributing. However, 
- I have already merged https://github.com/komuw/sewer/pull/125 which stopped `sewer` from redefining the root logger. Does that PR take care of the issues you intended to fix? If so, can we close this PR? If not, can we instead open up a github issue to discuss that?

**Comment by mmaney** [comment]
Ah... #125, which I hadn't noticed before, may be the cause of my seeing duplicated messages (see bug #136).  I believe that #125 was a step in the right direction which exposed the problem in #136 which had been "hidden by luck" more or less before that.

This seems to add complications for no benefit (and has the same bug with checking logger.handlers to decide if there's an ancestral handler already).  -1

**Comment by mmaney** [comment]
The issue with double-logged messages has long since been addressed by using the logging system as recommended by the Python library authors.  #136

**Pull request closed without merging**
